spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_database
    username: admin
    password: admin-gespyme-2024-99Pabcde
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: authenticator
  cloud:
    config:
      enabled: false
    aws:
      paramstore:
        enabled: false
  token:
    expiration_time:
server:
  port: 8082

  spring:


